linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - durationcheck
    - errname
    - errorlint
    - gocheckcompilerdirectives
    - goconst
    - gosec
    - importas
    - makezero
    - mirror
    - misspell
    - musttag
    - nilnil
    - usetesting
    - thelper
    - tparallel
    - unconvert
    - wastedassign
    - zerologlint
    # - exhaustruct
    # - goerr113
    # - gofumpt
    # - ireturn
linters-settings:
  gosec:
    excludes:
      - G204
      - G404
#   exhaustruct:
#     # List of regular expressions to match struct packages and names.
#     # If this list is empty, all structs are tested.
#     # Default: []
#     include:
#       - 'example\.com/package\.ExampleStruct[\d]{1,2}'
#     # List of regular expressions to exclude struct packages and names from check.
#     # Default: []
#     exclude:
#       - 'cobra\.Command$'
