#!/usr/bin/env python3

import os
import argparse
import json
from scapy.utils import PcapReader
from scapy.layers.dot11 import RadioTap, Dot11, Dot11Elt
from dateutil.parser import parse
from intervaltree import Interval, IntervalTree
from datetime import datetime
from itertools import islice
from glob import glob
import pandas as pd
from itertools import islice
from collections import Counter, defaultdict
from loguru import logger

LIMIT_PER_PCAP = 1000


def sprint_bytes(num):
    """
    this function will convert bytes to MB.... GB... etc
    """
    for x in ["bytes", "KB", "MB", "GB", "TB"]:
        if num < 1024.0:
            return f"{num:.2f} {x}"
        num /= 1024.0


# Convert frequency to channel for 2.4GHz and 5GHz frequencies
def freq_to_channel(freq):
    if freq is None:
        return -1
    if freq == 2484:
        return 14
    elif freq < 2484:
        return (freq - 2407) // 5
    elif freq >= 4910 and freq <= 4980:
        return (freq - 4000) // 5
    elif freq <= 45000:  # DMG band lower limit
        return (freq - 5000) // 5
    else:
        return (freq - 59400) // 5


def analyze_packet(packet):
    analyzed = {}
    analyzed["observed_at"] = datetime.fromtimestamp(float(packet.time))
    analyzed["dbm_signal"] = packet.dBm_AntSignal
    transmitting_channel = None
    receiving_channel = None

    if RadioTap in packet:
        receiving_channel = freq_to_channel(packet[RadioTap].ChannelFrequency)
    if Dot11 in packet:
        analyzed["type"] = packet[Dot11].type
        analyzed["src"] = packet[Dot11].addr2
        analyzed["dst"] = packet[Dot11].addr1
    if Dot11Elt in packet:
        elt = packet[Dot11Elt]
        while isinstance(elt, Dot11Elt):
            if elt.ID == 3:  # DSset
                transmitting_channel = int.from_bytes(elt.info, "big")
            elt = elt.payload

    if transmitting_channel:
        transmitting_channel = transmitting_channel
        analyzed["channel"] = transmitting_channel
    elif receiving_channel:
        analyzed["channel"] = receiving_channel

    if not transmitting_channel:
        transmitting_channel = receiving_channel

    analyzed["rx_channel"] = receiving_channel
    analyzed["tx_channel"] = transmitting_channel
    return analyzed


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--data_dir", default="./data/", help="Path to the data directory"
    )
    args = parser.parse_args()

    hops = defaultdict(lambda: IntervalTree())
    events = []
    hop_counts = Counter()
    with open(os.path.join(args.data_dir, "events.jsonl"), "r") as f:
        for _, line in enumerate(f):
            e = json.loads(line)
            if e["type"] != "Hop":
                continue
            e = e["event"]
            start = int(parse(e["start"]).timestamp() * 1e6)
            end = int(parse(e["stop"]).timestamp() * 1e6)
            e["start_ts"] = start
            e["stop_ts"] = end
            events.append(e)
            # We assume, for now, that start:end is unique up to events, so
            # that we don't have to worry about appended overlapping events.
            hops[e["hop_action"]["channel"]][start:end] = e
            hop_counts[e["hop_action"]["channel"]] += 1

            # {
            #     'type': 'Hop',
            #     'event': {
            #         'iface': {
            #             'net_iface': {
            #                 'Index': 29,
            #                 'MTU': 2312,
            #                 'Name': 'wlp0s20f0u1u1u4',
            #                 'HardwareAddr': 'AMDKs2tr',
            #                 'Flags': 51,
            #             },
            #             'index': 5,
            #             'total': 18,
            #             'hopper': 'static',
            #         },
            #         'step': 0,
            #         'period': 100000000,
            #         'hop_action': {'index': 0, 'channel': 6},
            #         'hop_obs': {'packets': 6, 'channel_packets': {'6': 6}},
            #         'start': '2023-07-02T14:06:47.520019829-04:00',
            #         'stop': '2023-07-02T14:06:47.619894803-04:00',
            #         'dur': 99874963,
            #     },
            # }

            # if i > 0:
            #     import pdb
            #     pdb.set_trace()
            #     pass

    logger.info(f"loaded {len(events)} hop events: {dict(hop_counts.most_common())}")

    for e in events:
        # hop_action': {'channel': 4
        if e["iface"] != "wlan0":
            continue
        start, stop = e["start_ts"], e["stop_ts"]
        options = {
            c: max(
                (i.data["hop_obs"]["packets"] for i in hops[c][start:stop]), default=0
            )
            for c in range(1, 15)
        }
        regret = max(options.values()) - e["hop_obs"]["packets"]
        # {'iface': 'wlan1', 'step': 0, 'period_ms': 100, 'hop_action': {'index': 9, 'channel': 10}, 'hop_obs': {'packets': 0, 'channel_packets': {}}, 'start': '2023-07-04T23:03:22.336254393-04:00', 'stop': '2023-07-04T23:03:22.436898371-04:00', 'dur_ms': 100.64399, 'start_ts': 1688526202336254, 'stop_ts': 1688526202436898}
        print(
            (e["step"], e["hop_action"]["channel"], e["iface"]),
            (e["hop_obs"]["packets"], max(options.values()), regret),
            sorted(
                e["hop_obs"]["channel_packets"].items(),
                key=lambda x: x[1],
                reverse=True,
            ),
            sorted(options.items(), key=lambda x: x[1], reverse=True),
        )

    # rows = []
    # files = sorted(glob(os.path.join(args.data_dir, "*.pcap")))
    # for file in islice(files, None):
    #     file_size = os.path.getsize(file)
    #     try:
    #         packets = PcapReader(file)
    #     except Exception as e:
    #         logger.error(e)
    #         continue
    #     n = 0
    #     rx_counts = Counter()
    #     for packet in islice(packets, LIMIT_PER_PCAP):
    #         a = analyze_packet(packet)
    #         rows.append(a)
    #         n += 1
    #         rx_counts[a["rx_channel"]] += 1
    #     logger.info(
    #         f"finished analyzing {n} packets from {file} {sprint_bytes(file_size)}, ch={dict(rx_counts.most_common(3))}"
    #     )
    # df = pd.DataFrame(rows)
    # rx_counts = Counter(df["rx_channel"])
    # tx_counts = Counter(df["tx_channel"])
    # print("rx counts:", rx_counts.most_common())
    # print("tx counts:", tx_counts.most_common())

    # print(df[df["rx_channel"] == 6].sample(10))

    # for i, row in df[df["rx_channel"] == 6].iterrows():
    #     print(i, row)


if __name__ == "__main__":
    main()
